version: 0.2

frontend:
  phases:
    preBuild:
      commands:
        - echo Installing dependencies...
        - npm install
    build:
      commands:
        - echo Building the project...
        - npm run build  # This assumes 'npm run build' is your Vite build command

  artifacts:
    baseDirectory: dist  # Adjust this if your Vite project outputs to a different directory
    files:
      - '**/*'  # Include all files in the dist folder

  cache:
    paths:
      - node_modules/**/*