export const countries = [
    "United States",
    "Canada",
    "United Kingdom",
    "Australia",
    "India",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Brazil",
    "Mexico",
    "Japan",
    "China",
    "South Korea",
    "Russia",
    "South Africa",
    "Nigeria",
    "Argentina",
    "Colombia",
    "Netherlands",
    "Sweden",
    "Switzerland",
    "New Zealand",
  ];